<?php

// Plugin definition
$plugin = array(
  'title' => t('Two column reverse bootstrap stacked'),
  'category' => t('Bootstrap: 2 columns'),
  'icon' => 'twocol-reverse-bootstrap-stacked.png',
  'theme' => 'twocol-reverse-bootstrap-stacked',
  'css' => 'twocol-reverse-bootstrap-stacked.css',
  'regions' => array(
    'top' => t('Top'),
    'left' => t('Left side'),
    'right' => t('Right side'),
    'bottom' => t('Bottom'),
  ),
);
